export const personInfoData = [
  {
    id: 1,
    favourite: false,
    name: "Leanne Graham",
    email: "Sincere@april.biz",
    phone: "1-770-736-8031 x56442",
    website: "http://hildegard.org",
  },
  {
    id: 2,
    favourite: false,
    name: " Ervin Howell",
    email: "Shanna@melissa.tv",
    phone: "010-692-6593 x09125",
    website: "http://anastasia.net",
  },
  {
    id: 3,
    favourite: false,
    name: "Clementine Bauch",
    email: "Nathan@yesenia.net",
    phone: "1-463-123-4447",
    website: "http://ramiro.info",
  },
  {
    id: 4,
    favourite: false,
    name: "Patricia Lebsack",
    email: "Julianne.OConner@kory.org",
    phone: "493-170-9623 x156",
    website: "http://kale.biz",
  },
  {
    id: 5,
    favourite: false,
    name: "Chelsey Dietrich",
    email: "Lucio_Hettinger@annie.ca",
    phone: "(254)954-1289",
    website: "http://demarco.info",
  },
  {
    id: 6,
    favourite: false,
    name: "Mrs. Dennis Schulist",
    email: "Karley_Dach@jasper.info",
    phone: "1-770-736-8031 x56442",
    website: "http://hildegard.org",
  },
  {
    id: 7,
    favourite: false,
    name: "Kurtis Weissnat",
    email: "Telly.Hoeger@billy.biz",
    phone: "1-770-736-8031 x56442",
    website: "http://hildegard.org",
  },
  {
    id: 8,
    favourite: false,
    name: "Nicholas Runolfsdottir V",
    email: "Sherwood@rosamond.me",
    phone: "1-770-736-8031 x56442",
    website: "http://hildegard.org",
  },
];
